plugins {
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

version = mod_version
group = mod_group_id

subprojects {
    apply plugin: 'java-library'

    version = rootProject.version
    group = rootProject.group

    repositories {
        mavenCentral()
        maven {
            name = 'TwelveIterations'
            url = uri('https://maven.twelveiterations.com/repository/maven-public/')
            content {
                includeGroup 'net.blay09.mods'
            }
        }
        maven {
            name = 'ParchmentMC'
            url = uri('https://maven.parchmentmc.org/')
            content {
                includeGroup 'org.parchmentmc.data'
            }
        }
        maven {
            name = 'NeoForge'
            url = uri('https://maven.neoforged.net/releases')
        }
        maven {
            name = 'TencentCloudFallback'
            url = uri('https://mirrors.cloud.tencent.com/nexus/repository/maven-public/')
        }
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(ProcessResources).configureEach {
        filteringCharset = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}
